### ISSUE TITLE
Related work

### ISSUE THREAD

**Issue by gitrj95** [protesilaos/consult-denote#1]
Hello Prot. I hope you are well.

Before you get too deep, I wondered if you'd seen this: https://github.com/mclear-tools/consult-notes

**Comment by protesilaos** [comment]
> From: rj ***@***.***>
> Date: Wed, 27 Mar 2024 17:04:23 -0700
>
> Hello Prot. I hope you are well.
>
> Before you get too deep, I wondered if you'd seen this: https://github.com/mclear-tools/consult-notes

I am aware of it. It has a different focus than what I want to do here,
which is to keep the familiar interactions of Denote but simply add the
Consult features on top.

-- 
Protesilaos Stavrou
https://protesilaos.com
