### ISSUE TITLE
Allow configuration of CONSULT preview modalities

### ISSUE THREAD

**Issue by hapst3r** [protesilaos/consult-denote#11]
Hej prot,

I am experimenting with the preview modalities of CONSULT, i.e. trying to find out whether I want automatic and immediate preview, a delayed preview, or a preview when pressing a keybinding. In CONSULT, I do this via CONSULT-CUSTOMIZE for `:preview-key` and regarding the function(s) I am interested in.

If I see this correctly, you configure the modalities of CONSULT previews in the functions CONSULT-DENOTE-FILE-PROMPT, CONSULT-DENOTE-SELECT-LINKED-FILE-PROMPT, CONSULT-DENOTE-SILO-DIRECTORY-PROMPT with the function CONSULT--READ.

Would it be possible to add a configuration option that takes values such as those mentioned in the [CONSULT preview readme section](https://github.com/minad/consult?tab=readme-ov-file#live-previews) and feed the variable's value into `:preview-key` (would have to be added to the aforementioned functions)?

I hope my suggestion provides a straightforward solution for this problem.

Have a good day :)

**Comment by protesilaos** [comment]
On 2024-12-29 11:19, hapst3r wrote:

> Would it be possible to add a configuration option that takes values
> such as those mentioned in the CONSULT readme section [1] and feed the
> variable's value into :preview-key (would have to be added to the
> aforementioned functions)?

Yes, sure! Should we reuse what Consult already has, or do you think we 
need our own user option?

> I hope my suggestion provides a straightforward solution for this
> problem.

I have not looked into the code. It seems like an easy addition, but we 
will see. What matters is that we want to do it.

> Have a good day :)

You too!

**Comment by hapst3r** [comment]
I am not sure whether it is possible to use what CONSULT currently implements. I have tried to use CONSULT-CUSTOMIZE on CONSULT-DENOTE-FILE-PROMPT, but this just leads to preview not working (or at least, not working with a preview key). The code I tried:
```emacs-lisp
(consult-customize consult-denote-file-prompt :preview-key "M-.")
```

The one reason I see for a CONSULT-DENOTE-side configuration option is that I generally don't call any of the aforementioned functions by themselves (they override the DENOTE-functions when CONSULT-DENOTE-MODE is activated IIUC), so there needs to be a way to pass the values to CONSULT--READ other than an optional argument. 

However, it is perfectly possible that there are other options I don't know about.

**Comment by protesilaos** [comment]
On 2024-12-29 12:43, hapst3r wrote:
> I am not sure whether it is possible to use what CONSULT currently
> implements. I have tried to use CONSULT-CUSTOMIZE on
> CONSULT-DENOTE-FILE-PROMPT, but this just leads to preview not working
> (or at least, not working with a preview key). The code I tried:
> 
> (consult-customize consult-denote-file-prompt :preview-key "M-.")

That specific key did not work on my end because it was being overriden 
by something in the vertico-mode-map.

I tried these instead and they seem to work:

(setq consult-preview-key "<f1>")

(consult-customize consult-denote-grep :preview-key "<f2>")


So maybe we do not need anything on our end, other than have the user 
set up an appropriate key binding?

**Comment by hapst3r** [comment]
Yeah, you are absolutely right. I did not consider CONSULT-PREVIEW-KEY as an option. I will change the title so that other people wondering about the manual preview capacities of CONSULT-DENOTE-enhanced commands will find it more easily.

Thanks, have a good day :)

**Comment by protesilaos** [comment]
> From: hapst3r ***@***.***>
> Date: Sun, 29 Dec 2024 12:11:41 -0800
>
> Yeah, you are absolutely right. I did not consider CONSULT-PREVIEW-KEY
> as an option. I will change the title so that other people wondering
> about the manual preview capacities of CONSULT-DENOTE-enhanced
> commands will find it more easily.
>
> Thanks, have a good day :)

You are welcome! Have a good day as well!

-- 
Protesilaos Stavrou
https://protesilaos.com
