### ISSUE TITLE
File preview when using consult-denote-find

### ISSUE THREAD

**Issue by hapst3r** [protesilaos/consult-denote#6]
Hej prot,

I just found about the possibility to have a file content preview when using `consult-find` using the following invocation: `(consult-customize consult-find :state (consult--file-preview))` (found here: https://github.com/minad/consult/issues/837). I was like "great, that should work with consult-denote-find as well", but I am unable to set it up. 

I have tried several combinations of configuration options:
- Call the above invocation, wrapped in a user-defined function without arguments, in `consult-denote-mode-hook`
- Use use-package's `:after` keyword to consult-denote, hoping that it would respect the settings made in consult's package declaration
- Calling the above incovation, wrapped in a user-defined function without arguments, before activate `consult-denote-mode`
- Advice `consult-denote-find` with the above invocation, wrapped in a user-defined function without arguments

I am at my wits' end as to how to get file preview to work with this wonderful package. Do you happen to have an idea how to get it set up?

I am sorry, but I have no idea whether this is an issue proper or just my inability to properly configure it.

Have a good day,
hapster

**Comment by protesilaos** [comment]
> From: hapst3r ***@***.***>
> Date: Sat,  7 Sep 2024 05:26:39 -0700
>
> Hej prot,

Hello there!

> [... 15 lines elided]

> I am sorry, but I have no idea whether this is an issue proper or just
> my inability to properly configure it.

I remember this working out-of-the-box but now I have the same problem
as you. Let me give it a try in a few hours and report back to you.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by protesilaos** [comment]
I tried this with regular `consult-find` but I cannot get it to show any previews:

```elisp
(consult-customize consult-find :preview-key '(:debounce 0.5 any))
```

I remember this working until recently. Though I do not update my packages frequently...

Anyway, I am not sure what is happening here. I check if there is some new user option, but I did not notice anything.

Does the regular `consult-find` show previews on your end? Am I just imagining things or was it showing previews before?

**Comment by hapst3r** [comment]
`consult-find` does not show a file preview out of the box. It does however show a file preview when placing `(consult-customize consult-find :state (consult--file-preview))` in your configuration.

I checked using the following steps:
1. (package-initialize)
2. (require 'consult)
3. (require 'vertico)
4. (vertico-mode)
5. `consult-find` does not show a preview
6. (consult-customize consult-find :state (consult--file-preview))
7. `consult-find` does show a preview

**Comment by protesilaos** [comment]
> From: hapst3r ***@***.***>
> Date: Sun,  8 Sep 2024 00:15:02 -0700
>
> `consult-find` does not show a file preview out of the box. It does
> however show a file preview when placing `(consult-customize
> consult-find :state (consult--file-preview))` in your configuration.

I see. I remember this working before out-of-the-box, but maybe I had
configured it and I forgot.

Anyway, this line should do the trick then:

    (consult-customize consult-denote-find :state (consult--file-preview))

It seems to work on my end.

-- 
Protesilaos Stavrou
https://protesilaos.com

**Comment by hapst3r** [comment]
Yes, it works on my end as well. I didn't know `consult-customize` would work on `consult-denote-find`!

**Comment by hapst3r** [comment]
Yes, it works on my end as well. I didn't know `consult-customize` would work on `consult-denote-find`!

Thanks, I will close the issue now.
