### ISSUE TITLE
Idea: consult-denote-backlinks

### ISSUE THREAD

**Issue by hapst3r** [protesilaos/consult-denote#7]
Hi prot,

I just had an idea that seemed too good not to put out there, even though I have no idea if it is feasible or not, and how it would have to be implemented.

The idea is to have a new command (consult-denote-backlinks) which lets you preview backlinks to the current buffer via the consult interface. I know there already is consult-denote-find and consult-denote-grep, but those have different applications, and in my current understanding of the backlinks buffer (after reading manual and checking functionality on site) it is not suited for the workflow I'd like to implement.

The use case: I use denote to write excerpts of newspaper articles on international politics (among other things), where mentioned countries, international treatys and other entities have their own entry and are linked in the excerpt of the newspaper article. Now I'd love to use backlink previews to speedily review what I've already read or written in relation to a particular country, a treaty or another entity, when I am about to read a related article.

I'm not proficient in programming, but if it is at all possible to implement and if you're able to give me some pointers I feel very inclined to try to come up with a possible solution (might be slow and not very well programmed, though :D).

Let me know what you think, have a good day :)

**Comment by protesilaos** [comment]
I thought I was already doing this. It should work now with the existing command `denote-find-backlinks`: that one will show the backlinked files in the minibuffer, asking to visit one of them. Now there is the preview as well.

**Comment by hapst3r** [comment]
Thank you so much <3
